import { Person } from '../shared/model/person';

export const PERSONS: Person[] = [
  {
    personId: 1,
    firstName: 'Hydrogen',
    lastName: 'Hn',
    phoneNumber: 1111111111,
    email: 'hydrogen@gmail.com',
    status: 'Active',
  },
  {
    personId: 2,
    firstName: 'Helium',
    lastName: 'Hm',
    phoneNumber: 2222222222,
    email: 'helium@gmail.com',
    status: 'Active',
  },
  {
    personId: 3,
    firstName: 'Lithium',
    lastName: 'Lm',
    phoneNumber: 3333333333,
    email: 'lithium@gmail.com',
    status: 'Active',
  },
  {
    personId: 4,
    firstName: 'Beryllium',
    lastName: 'Bm',
    phoneNumber: 4444444444,
    email: 'beryllium@gmail.com',
    status: 'Active',
  },
  {
    personId: 5,
    firstName: 'Boron',
    lastName: 'Bn',
    phoneNumber: 555555555,
    email: 'boron@gmail.com',
    status: 'Active',
  },
  {
    personId: 6,
    firstName: 'Carbon',
    lastName: 'Cn',
    phoneNumber: 6666666666,
    email: 'carbon@gmail.com',
    status: 'Active',
  },
  {
    personId: 7,
    firstName: 'Nitrogen',
    lastName: 'Nn',
    phoneNumber: 7777777777,
    email: 'nitrogen@gmail.com',
    status: 'Inactive',
  },
  {
    personId: 8,
    firstName: 'Oxygen',
    lastName: 'On',
    phoneNumber: 8888888888,
    email: 'oxygen@gmail.com',
    status: 'Active',
  },
  {
    personId: 9,
    firstName: 'Fluorine',
    lastName: 'Fe',
    phoneNumber: 9999999999,
    email: 'fluorine@gmail.com',
    status: 'Inactive',
  },
  {
    personId: 10,
    firstName: 'Neon',
    lastName: 'Nn',
    phoneNumber: 101010101010,
    email: 'neon@gmail.com',
    status: 'Inactive',
  },
];
